# This file was generated by GoReleaser. DO NOT EDIT.
cask "isola" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "05e1e8669060b1481f7df51ff9bdb4a1c15deefb570c7bfe1421907a80582942"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "83dc8f60979cbf3ef4c1a5eb94bf66485e9e22ce671225ca24f07a1219348f42"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a51977531b26b9a5ead3b35ab917dcbd2323eb1d4b4bbff6f236695d566ef20"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "370f68e7f0786245e0d320040de967a53667f3ea4e3b7dea9b9ce54557d5e666"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_linux_arm64.tar.gz"
    end
  end

  name "isola"
  desc "Isolated dev environment for every git worktree: ports, proxy, and databases"
  homepage "https://github.com/cyucelen/isola"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isola"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/isola")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/isola"]
    end
  end

  # No zap stanza required

end
