# This file was generated by GoReleaser. DO NOT EDIT.
cask "isola" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b60dcfb2d60e9f509eb1000d6ed87c0279c82b5553406c06a1a732117e373630"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28abe4c8392bbf92be7ae77f05191f54ae3b9b90d75bb2102a015b540232d463"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e97c79b7a157e6aad7de2fdc7d3f63574cec62097ccd0e67b016561745ea696"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e3e64fbf6db2a0d143719904ec1c19a4397fc3cda12dde53e53665f092661d2"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_linux_arm64.tar.gz"
    end
  end

  name "isola"
  desc "Isolated dev environment for every git worktree: ports, proxy, and databases"
  homepage "https://github.com/cyucelen/isola"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isola"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/isola")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/isola"]
    end
  end

  # No zap stanza required

end
