# This file was generated by GoReleaser. DO NOT EDIT.
cask "isola" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "4156078fd5cdf2c7f28b453cfa3489557517b2be0f185fdda486303b6f28c4f8"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0953fa613d014827b0b31eacc1aa7f137120a35ca4ea8148ada20f3eb86a3a22"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0530ea4803c37966d9d0cbeedd89a434cd3bdc84754ad6863507ffc2c654591"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d55604b9dcf72b8164bb41dfec75ab7c6d511634d9d6d778e6661014bf325c7f"
      url "https://github.com/cyucelen/isola/releases/download/v#{version}/isola_#{version}_linux_arm64.tar.gz"
    end
  end

  name "isola"
  desc "Isolated dev environment for every git worktree: ports, proxy, and databases"
  homepage "https://github.com/cyucelen/isola"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isola"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/isola")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/isola"]
    end
  end

  # No zap stanza required

end
