# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portree < Formula
  desc "Git Worktree Server Manager"
  homepage "https://github.com/cyucelen/portree"
  version "0.3.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cyucelen/portree/releases/download/v0.3.0-beta.1/portree_0.3.0-beta.1_darwin_amd64.tar.gz"
      sha256 "37f529e3be90cc32b340b04c4d5d1ab5afae6a2a08f675f6b5edb9b7abc81519"

      define_method(:install) do
        bin.install "portree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cyucelen/portree/releases/download/v0.3.0-beta.1/portree_0.3.0-beta.1_darwin_arm64.tar.gz"
      sha256 "948dc613abc4ddeaf60cd546c9a320198f64d0254a05f10229853f86f825587e"

      define_method(:install) do
        bin.install "portree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyucelen/portree/releases/download/v0.3.0-beta.1/portree_0.3.0-beta.1_linux_amd64.tar.gz"
      sha256 "85c342a57e864fcacb4b16d3d28d03f509ee6615b656e4dabf07bb1456dd0d55"
      define_method(:install) do
        bin.install "portree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cyucelen/portree/releases/download/v0.3.0-beta.1/portree_0.3.0-beta.1_linux_arm64.tar.gz"
      sha256 "8105abc0bdef2b9649cb8be4037bdf9fa48dc3287368138abf3199f704e51be2"
      define_method(:install) do
        bin.install "portree"
      end
    end
  end

  test do
    system "#{bin}/portree", "version"
  end
end
